// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw1F-lHN-sxXSsU9MImfR9X5PvE7xHp3I',
    appId: '1:165397405082:android:0dd455946e8da43e89ee23',
    messagingSenderId: '165397405082',
    projectId: 'app-pengaduan-71ba1',
    storageBucket: 'app-pengaduan-71ba1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcgOwEA-moVk27TC5psgn_2JQEnGlUf-k',
    appId: '1:165397405082:web:5816c13d25fac7fc89ee23',
    messagingSenderId: '165397405082',
    projectId: 'app-pengaduan-71ba1',
    authDomain: 'app-pengaduan-71ba1.firebaseapp.com',
    storageBucket: 'app-pengaduan-71ba1.firebasestorage.app',
    measurementId: 'G-9XS41W84RT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrHu3BtwKgWitatjxDUrke-JKMFwRdgg0',
    appId: '1:165397405082:ios:151120ac91ed310889ee23',
    messagingSenderId: '165397405082',
    projectId: 'app-pengaduan-71ba1',
    storageBucket: 'app-pengaduan-71ba1.firebasestorage.app',
    iosBundleId: 'com.example.appPengaduan',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrHu3BtwKgWitatjxDUrke-JKMFwRdgg0',
    appId: '1:165397405082:ios:151120ac91ed310889ee23',
    messagingSenderId: '165397405082',
    projectId: 'app-pengaduan-71ba1',
    storageBucket: 'app-pengaduan-71ba1.firebasestorage.app',
    iosBundleId: 'com.example.appPengaduan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcgOwEA-moVk27TC5psgn_2JQEnGlUf-k',
    appId: '1:165397405082:web:ce07b60d7aac32c789ee23',
    messagingSenderId: '165397405082',
    projectId: 'app-pengaduan-71ba1',
    authDomain: 'app-pengaduan-71ba1.firebaseapp.com',
    storageBucket: 'app-pengaduan-71ba1.firebasestorage.app',
    measurementId: 'G-FEYPJVC0L9',
  );

}